version: "3.8"

services:
  dashborges:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000" # API port
      - "0.0.0.0:8501:8501" # Streamlit dashboard port
    volumes:
      - dashborges_data:/app/data
      - dashborges_config:/app/config
      - dashborges_logs:/app/logs
    environment:
      - DASHBORGES_DATA_DIR=/app/data
      - DASHBORGES_CONFIG_DIR=/app/config
      - DASHBORGES_LOGS_DIR=/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/transactions/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dashborges_data:
    driver: local
    # This volume stores all database files and user data
  dashborges_config:
    driver: local
    # This volume stores configuration files
  dashborges_logs:
    driver: local
    # This volume stores application logs
